# Generated by Django 5.1 on 2025-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('waiter', 'Waiter'), ('cashier', 'Cashier'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
