# Generated by Django 5.1 on 2025-09-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
