# Generated by Django 5.1 on 2025-09-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('confirmed', 'Confirmed')], default='Booked', max_length=20),
        ),
    ]
