# Generated by Django 5.1 on 2025-09-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_foodreview_servicereview_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='table',
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='waiter',
        ),
        migrations.DeleteModel(
            name='FoodReview',
        ),
        migrations.DeleteModel(
            name='ServiceReview',
        ),
    ]
